name: GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: npm ci
      - name: Build and Deploy
        env:
          NODE_ENV: production
          # Google tag
          REACT_APP_GA_TRACKING_ID: G-JCRZM0ZRZ0
          # This is set automatically by github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/anthonybuncio/personal-site.git
          npm run deploy
